#spring.thymeleaf.prefix=classpath:/static/

spring:
  profiles:
    group:
      "local": "local, common"
      "dev":  "dev,common"
      "prod": "real,common"
---
spring:
  config:
    activate:
      on-profile: "common"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8080
---
spring:
    config:
      activate:
        on-profile: local
logging:
  config: classpath:log4j2-local.yml
---

