#spring.thymeleaf.prefix=classpath:/static/

spring:
  profiles:
    group:
      "local": "local, common, h2-database"
      "dev":  "dev,common"
      "prod": "real,common"
---
spring:
  config:
    activate:
      on-profile: "common"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: html
    cache: true
---
spring:
    config:
      activate:
        on-profile: local
server:
  port : 8080
  undertow:
    threads:
      io: 16
      worker: 400
logging:
  config: classpath:log4j2-local.yml
---
spring:
  config:
    activate:
      on-profile: h2-database
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/Documents/h2db/study;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernsate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
---
